export PYTHONPATH=<path to python projects>

# User specific aliases and functions
alias clr='clear '

alias gcl='git clone '
alias gs='git status '
alias gl='git log '
alias gd='git diff '
alias ga='git add '
alias gr='git reset '
alias gc='git commit -m '
alias gb='git branch '
alias gf='git log —follow — '
alias gg='git log —all —graph —decorate '
alias gch='git checkout '
alias gpu='git push '
alias gpl='git pull '
alias gbf="git rev-list --objects --all | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' | awk '/^blob/ {print substr($0,6)}' | sort --numeric-sort --key=2 | tail | cut --complement --characters=13-40 | numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest "

alias tb='tensorboard --logdir=. '
alias ap='autopep8 -r --in-place . '

alias pi='pip install -e . '

alias ca='conda activate '
alias cak='conda activate keras '
alias cab='conda activate base '
alias cac='conda activate cpp '
alias cu='conda update '
alias ci='conda install '
alias cl='conda list '
alias cs='conda search '
alias cc='conda create -n '
alias cel='conda env list '
alias cu='conda uninstall '
alias cr='conda remove -n '
alias cutp='conda uninstall tensorflow keras tensorflow-gpu keras-gpu tensorflow-tensorboard pytorch torchvision cudatoolkit pytorch-cpu torchvision-cpu -y '
alias citc='conda install tensorflow keras tensorflow-tensorboard -y '
alias citg='conda install tensorflow-gpu keras-gpu tensorflow-tensorboard -y '
alias cic='conda install valgrind gcc conda git cmake -y '
alias cib='conda install autopep8 pandas matplotlib qt pyqt pyqtgraph ipython conda numpy pip python opencv git pillow cmake -y '
alias cif='conda install autopep8 pandas matplotlib qt pyqt pyqtgraph conda numpy pip python opencv git pillow cmake click flask flake8 mypy pydocstyle pytest pylint pep8 seaborn numba setuptools sortedcollections sortedcontainers typing pyinstaller h5py -y '
alias ciftc='conda install tensorflow keras tensorflow-tensorboard autopep8 pandas matplotlib qt pyqt pyqtgraph conda numpy pip python opencv git pillow cmake click flask flake8 mypy pydocstyle pytest pylint pep8 seaborn numba setuptools sortedcollections sortedcontainers typing pyinstaller h5py -y '
alias ciftg='conda install tensorflow-gpu keras-gpu tensorflow-tensorboard autopep8 pandas matplotlib qt pyqt pyqtgraph conda numpy pip python opencv git pillow cmake click flask flake8 mypy pydocstyle pytest pylint pep8 seaborn numba setuptools sortedcollections sortedcontainers typing pyinstaller h5py -y '
alias cipc='conda install pytorch-cpu torchvision-cpu -y '
alias cipg='conda install pytorch torchvision -y '
alias cifpc='conda install pytorch-cpu torchvision-cpu autopep8 pandas matplotlib qt pyqt pyqtgraph conda numpy pip python opencv git pillow cmake click flask flake8 mypy pydocstyle pytest pylint pep8 seaborn numba setuptools sortedcollections sortedcontainers typing pyinstaller h5py -y '
alias cifpg='conda install pytorch torchvision autopep8 pandas matplotlib qt pyqt pyqtgraph conda numpy pip python opencv git pillow cmake click flask flake8 mypy pydocstyle pytest pylint pep8 seaborn numba setuptools sortedcollections sortedcontainers typing pyinstaller h5py -y '

alias sa='source ~/anaconda3/bin/activate '
